name = "cacher2"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cacher2"
database_id = "8175ca2c-c339-460a-b83b-b093a8a19c5b"

[vars]
WORLDS = '{"dev":"cacher2-dev"}'

# Secrets (set via `wrangler secret put`):
# ROOT_API_KEY
# R2_ACCOUNT_ID
# R2_ACCESS_KEY_ID
# R2_SECRET_ACCESS_KEY

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1